=== bjbm94/Actividad-7-2/Biblioteca.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="biblioteca">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="bibliotecario">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="apellidos" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="lector">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:string" />
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="apellidos" type="xs:string" />
                            <xs:element name="telÃ©fono" type="xs:positiveInteger" minOccurs="0" maxOccurs="1" />
                            <xs:element name="direccion">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tipo_de_calle">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="Calle"/>
                                                    <xs:enumeration value="Avenida"/>
                                                    <xs:enumeration value="Plaza"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="nombre_calle" type="xs:string" />
                                        <xs:element name="numero" type="xs:positiveInteger" />
                                        <xs:element name="piso_y_letra" type="xs:string" />
                                        <xs:element name="codigo_postal" type="xs:positiveInteger" />
                                        <xs:element name="localidad" type="xs:string" />
                                        <xs:element name="provincia" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="prestamo" maxOccurs="3">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fecha">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="inico" type="xs:string" />
                                        <xs:element name="devolucion" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="ejemplar">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="numero_de_registro" type="xs:integer" />
                                        <xs:element name="titulo" type="xs:string" />
                                        <xs:element name="autor" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="identificador" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== bjbm94/Actividad-7-2/Biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="Biblioteca.xsd">
    <bibliotecario>
        <nombre>Juan</nombre>
        <apellidos>García Ortega</apellidos>
    </bibliotecario>
    <lector>
        <id>78538240W</id><!-- Aquí puse mi DNI por poner algo -->
        <nombre>Bryan</nombre>
        <apellidos>Barral Medina</apellidos>
        <teléfono>690808003</teléfono>
        <direccion>
            <tipo_de_calle>Calle</tipo_de_calle>
            <nombre_calle>Seguidilla</nombre_calle>
            <numero>18</numero>
            <piso_y_letra>1A</piso_y_letra>
            <codigo_postal>35620</codigo_postal>
            <localidad>Gran Tarajal</localidad>
            <provincia>Las Palmas</provincia>
        </direccion>
    </lector>
    <prestamo identificador="12b45"><!-- Esto lo represento con números y letras, por inventarme algo -->
        <fecha>
            <inico>2021-11-20</inico>
            <devolucion>2021-12-20</devolucion>
        </fecha>
        <ejemplar>
            <numero_de_registro>12</numero_de_registro><!-- Este lo represento solo con números -->
            <titulo>Don Quijote de la Mancha</titulo>
            <autor>miguel de Cervantes</autor>
        </ejemplar>
    </prestamo>
</biblioteca>
